name: dram2-env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=1.5.2
  - pytest=7.2.0
  - scikit-bio=0.5.7
  - mmseqs2==15.6f452
  - hmmer=3.3.2
  - scipy=1.8.1
  - sqlalchemy=1.4.46
  - barrnap=0.9
  - altair=4.2.0
  - openpyxl=3.0.10
  - networkx=2.8.8
  - ruby=3.1.2
  - parallel=20221122
  - trnascan-se=2.0.12
  - biopython=1.83
  - prodigal=2.6.3
  - samtools=1.17
  - bowtie2=2.5.1
  - ncurses
  - quast=5.2.0
  - bbtools
  - pip:
      - matplotlib==3.8.3
