name: Feature request
description: Suggest an idea for the DRAM. DRAMv1 is no longer getting new features. But new feature requests for DRAMv1 may be moved to DRAMv2
labels: enhancement
body:
  - type: textarea
    id: description
    attributes:
      label: Description of feature
      description: Please describe your suggestion for a new feature. It might help to describe a problem or use case, plus any alternatives that you have considered.
    validations:
      required: true
