name: dram2-env
channels:
  - conda-forge
  - bioconda
  - defaults
  - agbiome

dependencies:
  - python=3.10
  - pandas=1.5.2
  - pytest=7.2.0
  - scikit-bio=0.5.7
  - mmseqs2==15.6f452
  - hmmer=3.3.2
  - scipy=1.8.1
  - sqlalchemy=1.4.46
  - barrnap=0.9
  - ruby=3.1.2
  - parallel=20221122
  - trnascan-se=2.0.12
  - biopython=1.83
  - prodigal=2.6.3
  - samtools=1.17
  - bowtie2=2.5.1
  - seqtk
  - ncurses
  - bbmap
  - openpyxl=3.1.2
  - pplacer=1.1.alpha19
  - mafft=7.525

  # visualization packages
  - click
  - numpy
  - networkx>2,<3
  - panel>1,<2
  - bokeh>3,<4

  - pip:
      - matplotlib==3.8.3
      - ete3
      - etetoolkit
